name: Build and Deploy Prod

on:
  push:
    branches:
      - 'main'

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          tags: |
            ghcr.io/vzauartcc/ui:${{ github.sha }}
            ghcr.io/vzauartcc/ui:master
            ghcr.io/vzauartcc/ui:buildcache
          cache-from: type=registry,ref=ghcr.io/vzauartcc/ui:buildcache
          cache-to: type=registry,ref=ghcr.io/vzauartcc/ui:buildcache,mode=max

  Deploy-to-Prod:
    needs: Build-and-Push
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Initialize doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log into K8s cluster
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zau-k8s

      - name: Deploy image to cluster
        run: kubectl set image deployment/ui ui=ghcr.io/vzauartcc/ui:${{ github.sha }} --record -n zau-web-stack

      - name: Verify deployment
        run: kubectl rollout status deployment/ui -n zau-web-stack
